image: harbor.uni-muenster.de/proxy-docker/eclipse-temurin:17-alpine

stages:
  - test
  - deploy

cache:
  paths:
    - .m2/repository
    - default-oxygen-frameworks

# For merge requests do not `deploy` but only run `verify`.
test:
  stage: test
  script:
    - ./mvnw verify

# deploy using ci_settings.xml as maven settings
# see https://gitlab.com/help/user/packages/maven_repository/index.md#creating-maven-packages-with-gitlab-cicd-using-maven
deploy-package:
  stage: deploy
  script:
    - ./mvnw -Drevision=$CI_COMMIT_TAG -Dchangelist="" clean deploy -s ci_settings.xml
  artifacts:
    paths:
      - target
  only:
    # https://gitlab.com/gitlab-org/gitlab-foss/-/issues/27818
    variables:
      - $CI_COMMIT_TAG =~ /^\d+.\d+.\d+$/


pages:
  stage: deploy
  script:
    - mkdir -p public
    - ls -la
    - cp -v target/*-package.zip public/
    - cp -v target/descriptor.xml public/descriptor.xml
  needs:
    - deploy-package
  artifacts:
    paths:
      - public
  only:
    # https://gitlab.com/gitlab-org/gitlab-foss/-/issues/27818
    variables:
      - $CI_COMMIT_TAG =~ /^\d+.\d+.\d+$/
